In [1]:
import pandas as pd

# Коннект с гугл диском
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Чтение таблиц

## aircraft.csv

In [2]:
aircraft = pd.read_csv('/content/drive/My Drive/Анализ_данных/ЛР_1_air_stats/aircraft.csv', encoding = 'utf-8', sep=';')

aircraft

,Вид воздушного судна,Тип (наименование) воздушного судна,Опознавательные знаки,Серийный №,Идентификац. №,номер свидетельства о регистрации,дата действующего свидетельства о регистрации
0,самолет,Птенец-2,RA-0001A,NaN,ЕЭВС.03.1529,0001,11.03.2012
1,дельталет,Аватар,RA-0002A,NaN,ЕЭВС.03.1709,0002,16.03.2012
2,самолет,С-2 Елочка,RA-0002G,NaN,ЕЭВС.02.0126,0224,02.06.2006
3,дельталет,СОКОЛ,RA-0003A,NaN,ЕЭВС.03.1708,0003,16.03.2012
4,самолет,Небесный,RA-0003G,NaN,ЕЭВС.02.0013,0225,07.04.2008
...,...,...,...,...,...,...,...
8928,самолет,Ан-2,RA-96247,1Г7231,NaN,3599,20.07.1966
8929,самолет,Ан-2,RA-96249,1Г7233,NaN,3600,20.07.1966
8930,самолет,Ан-2,RA-96252,1Г7236,NaN,3629,27.04.2012
8931,самолет,Ан-2,RA-96255,1Г7239,NaN,3657,25.05.2000
8932,самолет,Як-40,RA-98114,9731549,NaN,6747,03.03.1988

## airports.csv

In [3]:
airports = pd.read_csv('/content/drive/My Drive/Анализ_данных/ЛР_1_air_stats/airports.csv')

airports

,Наименование аэропорта РФ,Свидетельство,Юрлицо,Тип
0,Архангельск (Талаги),"Сертификат МАК № 061А-М, 27.09.2013-03.08.2018...",ОАО «Аэропорт Архангельск»,В
1,"Нарьян-Мар В 3 км восточнее г.Нарьян-Мар, НАО",Свидетельство о государственной регистрации и ...,ОАО «Нарьян-Марский объединенный авиаотряд»,В
2,"Васьково 12 км юго-западнее г.Архангельск, Ар...",Свидетельство о государственной регистрации и ...,ОАО «2-ой Архангельский объединенный авиаотряд»,Г
3,"Котлас 3 км юго-восточнее г.Котлас, Архангель...",Свидетельство о государственной регистрации и ...,ОАО «Аэросервис»,Г
4,"Лешуконское 1,3 км юго-западнее села Лешуконс...",Свидетельство о государственной регистрации и ...,ОАО «Аэропорт Лешуконское»,Г
...,...,...,...,...
277,Ургалан,Свидетельство о государственной регистрации аэ...,ОАО «АС «Амур»,Г
278,Итуруп,Сертификат Росавиации № АД 00014 19.09.2014 ...,КП «Аэропорты Курильских островов»,В
279,Домодедово,Сертификат МАК № 013 А-М 29.08.2011 29.08.2016,ЗАО «МЕЖДУНАРОДНЫЙ АЭРОПОРТ «ДОМОДЕДОВО»,А
280,Внуково,Сертификат МАК № 015 А-М 15.01.2015 01.02.2020,ОАО «Аэропорт Внуково»,Б
281,Шереметьево,Сертификат МАК № 008 А-М 14.12.2010 31.12.2015,ОАО «Международный аэропорт Шереметьево»,А

## airlines.csv

In [4]:
airlines = pd.read_csv('/content/drive/My Drive/Анализ_данных/ЛР_1_air_stats/airlines.csv')

airlines

,Индекс,Название,Юридическое Название,Самолеты
551,Абакан Эир,Общество с ограниченной ответственностью «АБАК...,Абакан,"Ил-76 (7), Ми-26 (3), Ми-8 (3), Ми-8МТВ (5)"
481,Авиа Менеджмент Груп,Акционерное общество «Авиа Менеджмент Груп»,Иваново (Южный),Pilatus PC-12 (10)
554,Авиакомпания «Лайт Эйр»,Закрытое акционерное общество Авиакомпания «Ла...,Уфа,"BK-117 (1), Robinson R-44 (17), Ан-2 (7), R..."
284,Авиакомпания СОКОЛ,Закрытое акционерное общество Авиакомпания «С...,Новотитаровская-Азимут,"Ми-2 (1), Ми-8 (1)"
442,Авиакон Цитотранс,Открытое акционерное общество Авиакомпания «А...,Екатеринбург(Кольцово),Ил-76 (5)
...,...,...,...,...
526,Ямал АК ООО,Общество с ограниченной ответственностью «Авиа...,Салехард Тазовский Тарко-Сале,"AS-350 (2), Ми-8 (41), Ми-8МТВ (3)"
142,Ямал АТК ОАО,Открытое акционерное общество «Авиационная тра...,Москва (Домодедово) Салехард Тюмень(Рощино),"A-320 (7), A-321 (2), B-737 (4), CL-600-2B1..."
463,"2-й Архангельский ОАО, ОАО",Открытое акционерное общество «2-ой Архангельс...,Архангельск (Васьково),"L-410 (4), Ан-2 (6), Ми-26 (2), Ми-8 (9), ..."
239,223-й ЛО ФГКУ,федеральное государственное казенное учреждени...,Чкаловский,"Ил-62 (4), Ил-76 (5), Ту-154 (4)"
529,224-й ЛО ОАО,Открытое акционерное общество «Государственная...,Тверь(Мигалово),"Ан-124 (8), Ил-76 (17)"

## passenger_transportation.csv

In [5]:
passenger_transportation = pd.read_csv('/content/drive/My Drive/Анализ_данных/ЛР_1_air_stats/passenger_transportation.csv', sep = ';')

passenger_transportation

,Наименование аэропорта РФ,Год периода данных,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь,Январь - Декабрь
0,Абакан,2018,11 851,10 504,11 591,12 323,14 314,19 935,25 213,25 507,19 295,NaN,NaN,NaN,NaN
1,Айхал,2018,***,***,***,***,***,***,***,***,***,NaN,NaN,NaN,NaN
2,Алдан,2018,***,***,***,***,***,***,***,***,***,NaN,NaN,NaN,NaN
3,Амдерма,2018,***,***,***,***,***,***,***,***,***,NaN,NaN,NaN,NaN
4,Анадырь,2018,5 128,4 447,5 456,7 650,8 364,10 563,13 402,13 751,10 065,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3468,Якутск,2007,27636,25976,34291,38803,38478,59142,67295,75257,52681,44505,40439,41074,545577
3469,Якутск(Маган),2007,***,***,***,***,***,***,***,***,***,***,***,***,***
3470,Ямбург,2007,6239,3195,6648,6268,6088,6028,5975,6024,6262,6451,6968,6480,72626
3471,Ярославль(Туношна),2007,557,720,650,411,328,864,688,965,883,505,640,1066,8277
3472,Ярцево,2007,***,***,***,***,***,***,***,***,***,***,***,***,***

## cargo_transportation.csv

In [6]:
cargo_transportation = pd.read_csv('/content/drive/My Drive/Анализ_данных/ЛР_1_air_stats/cargo_transportation.csv', sep = ';')

cargo_transportation

,Наименование аэропорта РФ,Год периода данных,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь,Январь - Декабрь
0,Абакан,2018,"63,39","60,98","69,46","88,62","83,81","64,99","49,64","70,26","87,35",NaN,NaN,NaN,NaN
1,Айхал,2018,***,***,***,***,***,***,***,***,***,NaN,NaN,NaN,NaN
2,Алдан,2018,***,***,***,***,***,***,***,***,***,NaN,NaN,NaN,NaN
3,Амдерма,2018,***,***,***,***,***,***,***,***,***,NaN,NaN,NaN,NaN
4,Анадырь,2018,"112,58","267,65","221,77","331,37","160,45","89,77","109,29","95,99","103,77",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3468,Якутск,2007,"583,7","707,8","851,8",1018,"950,8",900,"1154,9","1137,84","1485,5","1382,5",1488,"1916,6","13577,44"
3469,Якутск(Маган),2007,***,***,***,***,***,***,***,***,***,***,***,***,***
3470,Ямбург,2007,"3,55","0,16","3,37","5,32","4,31","6,3","6,88","3,6","4,13","4,93","4,17","8,87","55,59"
3471,Ярославль(Туношна),2007,847,"1482,9","1325,4","1235,97",629,838,"1211,3",915,"1249,6","1650,5","1822,6","2055,6","15262,87"
3472,Ярцево,2007,***,***,***,***,***,***,***,***,***,***,***,***,***

# 1. Построить список уникальных типов самолетов, зарегистрированных в России.

In [7]:
aircraft = aircraft.fillna(0)

aircraft

,Вид воздушного судна,Тип (наименование) воздушного судна,Опознавательные знаки,Серийный №,Идентификац. №,номер свидетельства о регистрации,дата действующего свидетельства о регистрации
0,самолет,Птенец-2,RA-0001A,0,ЕЭВС.03.1529,0001,11.03.2012
1,дельталет,Аватар,RA-0002A,0,ЕЭВС.03.1709,0002,16.03.2012
2,самолет,С-2 Елочка,RA-0002G,0,ЕЭВС.02.0126,0224,02.06.2006
3,дельталет,СОКОЛ,RA-0003A,0,ЕЭВС.03.1708,0003,16.03.2012
4,самолет,Небесный,RA-0003G,0,ЕЭВС.02.0013,0225,07.04.2008
...,...,...,...,...,...,...,...
8928,самолет,Ан-2,RA-96247,1Г7231,0,3599,20.07.1966
8929,самолет,Ан-2,RA-96249,1Г7233,0,3600,20.07.1966
8930,самолет,Ан-2,RA-96252,1Г7236,0,3629,27.04.2012
8931,самолет,Ан-2,RA-96255,1Г7239,0,3657,25.05.2000
8932,самолет,Як-40,RA-98114,9731549,0,6747,03.03.1988

In [10]:
# Список ВС, зарегистрированных в России (присутствует номер свидетельства о регистрации)
unique_rus_aircrafts = aircraft[aircraft['номер свидетельства о регистрации'] != 0]

# Уникальные типы самолетов среди ВС, зарегистрированных в России
unique_rus_aircrafts = list(unique_rus_aircrafts[unique_rus_aircrafts['Вид воздушного судна'] == 'самолет']['Тип (наименование) воздушного судна'].unique())

print('Cписок уникальных типов самолетов, зарегистрированных в России:\n', unique_rus_aircrafts)
print('Количество:', len(unique_rus_aircrafts))

Cписок уникальных типов самолетов, зарегистрированных в России:

# 2. Какой тип самолета имеет самую позднюю дату выдчи сертификата.

In [11]:
# Самая поздняя дата выдачи сертификата
aircraft['дата действующего свидетельства о регистрации'] = aircraft['дата действующего свидетельства о регистрации'].astype("datetime64[ns]")
latest_date = max(list(aircraft['дата действующего свидетельства о регистрации']))

latest_date

Timestamp('2017-12-22 00:00:00')

In [12]:
# Тип самолета с самой поздней датой выдачи сертификата
plane_type = aircraft.loc[aircraft['дата действующего свидетельства о регистрации'] == latest_date]['Тип (наименование) воздушного судна']

print('Тип самолета с самой поздней датой выдачи сертификата:', list(plane_type)[0])

Тип самолета с самой поздней датой выдачи сертификата: E 330 LXK

# 3. Построить запрос: Владелец Аэропорта, Аэропорт, Пассажиропоток суммарный за 2018, грузопоток суммарный за 2018.

In [13]:
passenger_transportation = passenger_transportation.fillna(0)
passenger_transportation = passenger_transportation.replace('***', 0)

# Список месяцев
months = list(passenger_transportation.columns)
months.pop(0)
months.pop(0)

# Преобразование значений пассажиропотока в вещественный тип
for mon in months:
  passenger_transportation[mon] = passenger_transportation[mon].apply(lambda x: str(x).replace(' ', ''))
  passenger_transportation[mon] = passenger_transportation[mon].astype(float)

# Вычисление годовых значений пассажиропотока
passenger_transportation['Январь - Декабрь'] = passenger_transportation.iloc[:, 2:-1].sum(axis=1)

passenger_transportation

,Наименование аэропорта РФ,Год периода данных,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь,Январь - Декабрь
0,Абакан,2018,11851.0,10504.0,11591.0,12323.0,14314.0,19935.0,25213.0,25507.0,19295.0,0.0,0.0,0.0,150533.0
1,Айхал,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Алдан,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Амдерма,2018,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Анадырь,2018,5128.0,4447.0,5456.0,7650.0,8364.0,10563.0,13402.0,13751.0,10065.0,0.0,0.0,0.0,78826.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3468,Якутск,2007,27636.0,25976.0,34291.0,38803.0,38478.0,59142.0,67295.0,75257.0,52681.0,44505.0,40439.0,41074.0,545577.0
3469,Якутск(Маган),2007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3470,Ямбург,2007,6239.0,3195.0,6648.0,6268.0,6088.0,6028.0,5975.0,6024.0,6262.0,6451.0,6968.0,6480.0,72626.0
3471,Ярославль(Туношна),2007,557.0,720.0,650.0,411.0,328.0,864.0,688.0,965.0,883.0,505.0,640.0,1066.0,8277.0
3472,Ярцево,2007,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
cargo_transportation = cargo_transportation.fillna(0)
cargo_transportation = cargo_transportation.replace('***', 0)

# Список месяцев
months = list(cargo_transportation.columns)
months.pop(0)
months.pop(0)

# Преобразование значений грузопотока в вещественный тип
for mon in months:
  cargo_transportation[mon] = cargo_transportation[mon].apply(lambda x: str(x).replace(' ', ''))
  cargo_transportation[mon] = cargo_transportation[mon].apply(lambda x: str(x).replace(',', '.'))
  cargo_transportation[mon] = cargo_transportation[mon].astype(float)

# Вычисление годовых значений грузопотока
cargo_transportation['Январь - Декабрь'] = cargo_transportation.iloc[:, 2:-1].sum(axis=1)

cargo_transportation

,Наименование аэропорта РФ,Год периода данных,Январь,Февраль,Март,Апрель,Май,Июнь,Июль,Август,Сентябрь,Октябрь,Ноябрь,Декабрь,Январь - Декабрь
0,Абакан,2018,63.39,60.98,69.46,88.62,83.81,64.99,49.64,70.26,87.35,0.00,0.00,0.00,638.50
1,Айхал,2018,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,Алдан,2018,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,Амдерма,2018,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,Анадырь,2018,112.58,267.65,221.77,331.37,160.45,89.77,109.29,95.99,103.77,0.00,0.00,0.00,1492.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3468,Якутск,2007,583.70,707.80,851.80,1018.00,950.80,900.00,1154.90,1137.84,1485.50,1382.50,1488.00,1916.60,13577.44
3469,Якутск(Маган),2007,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3470,Ямбург,2007,3.55,0.16,3.37,5.32,4.31,6.30,6.88,3.60,4.13,4.93,4.17,8.87,55.59
3471,Ярославль(Туношна),2007,847.00,1482.90,1325.40,1235.97,629.00,838.00,1211.30,915.00,1249.60,1650.50,1822.60,2055.60,15262.87
3472,Ярцево,2007,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [15]:
# Список номеров строк, в которых наименование аэропорта мужно срезать до пробела
by_space = [1, 2, 3, 4, 5, 6, 8, 9, 10, 13, 14, 15, 16, 17]

for i in by_space:
  ind = airports.loc[i, 'Наименование аэропорта РФ'].index(' ')
  airports.loc[i, 'Наименование аэропорта РФ'] = airports.loc[i, 'Наименование аэропорта РФ'][:ind]

# Ручная корректировка некоторых наименований аэропортов
airports.loc[7, 'Наименование аэропорта РФ'] = 'Нижняя Пеша'
airports.loc[11, 'Наименование аэропорта РФ'] = 'Летняя  Золотица'
airports.loc[12, 'Наименование аэропорта РФ'] = 'Верхняя Золотица'
airports.loc[18, 'Наименование аэропорта РФ'] = 'Каменка'
airports.loc[19, 'Наименование аэропорта РФ'] = 'Несь'
airports.loc[210, 'Наименование аэропорта РФ'] = 'Ярославль (Туношна)'
airports.loc[228, 'Наименование аэропорта РФ'] = 'Челябинск'

# Удаление ненужных пробелов из наименований аэропортов
airports['Наименование аэропорта РФ'] = airports['Наименование аэропорта РФ'].apply(lambda x: str(x).replace(' (', '('))
airports['Наименование аэропорта РФ'] = airports['Наименование аэропорта РФ'].apply(lambda x: str(x).rstrip().lstrip())

In [16]:
airports

,Наименование аэропорта РФ,Свидетельство,Юрлицо,Тип
0,Архангельск(Талаги),"Сертификат МАК № 061А-М, 27.09.2013-03.08.2018...",ОАО «Аэропорт Архангельск»,В
1,Нарьян-Мар,Свидетельство о государственной регистрации и ...,ОАО «Нарьян-Марский объединенный авиаотряд»,В
2,Васьково,Свидетельство о государственной регистрации и ...,ОАО «2-ой Архангельский объединенный авиаотряд»,Г
3,Котлас,Свидетельство о государственной регистрации и ...,ОАО «Аэросервис»,Г
4,Лешуконское,Свидетельство о государственной регистрации и ...,ОАО «Аэропорт Лешуконское»,Г
...,...,...,...,...
277,Ургалан,Свидетельство о государственной регистрации аэ...,ОАО «АС «Амур»,Г
278,Итуруп,Сертификат Росавиации № АД 00014 19.09.2014 ...,КП «Аэропорты Курильских островов»,В
279,Домодедово,Сертификат МАК № 013 А-М 29.08.2011 29.08.2016,ЗАО «МЕЖДУНАРОДНЫЙ АЭРОПОРТ «ДОМОДЕДОВО»,А
280,Внуково,Сертификат МАК № 015 А-М 15.01.2015 01.02.2020,ОАО «Аэропорт Внуково»,Б
281,Шереметьево,Сертификат МАК № 008 А-М 14.12.2010 31.12.2015,ОАО «Международный аэропорт Шереметьево»,А

In [17]:
# Создание датафрейма под запрос
request = pd.DataFrame()

# Добавление стобцов 'Юрлицо' и 'Наименование аэропорта РФ' из airports
request['Юрлицо'] = airports['Юрлицо']
request['Наименование аэропорта РФ'] = airports['Наименование аэропорта РФ']

# Извлечение данных о пассажиропотоке за 2018 год
pt_2018 = passenger_transportation.loc[passenger_transportation['Год периода данных'] == 2018]

# Наполнение request соответствующими данными о пассажиропотоке за 2018 год
# try/except пропускает аэропорты, о пассажиропотоке которых нет информации
for i in list(request['Наименование аэропорта РФ']):
  try:
    request.loc[(request['Наименование аэропорта РФ'] == i), 'Пассажиропоток суммарный за 2018'] = int(pt_2018.loc[pt_2018['Наименование аэропорта РФ'] == i]['Январь - Декабрь'])
  except:
    continue


# Извлечение данных о грузопотоке за 2018 год
ct_2018 = cargo_transportation.loc[cargo_transportation['Год периода данных'] == 2018]

# Наполнение request соответствующими данными о грузопотоке за 2018 год
# try/except пропускает аэропорты, о грузопотоке которых нет информации
for i in list(request['Наименование аэропорта РФ']):
  try:
    request.loc[(request['Наименование аэропорта РФ'] == i), 'Грузопоток суммарный за 2018'] = int(ct_2018.loc[ct_2018['Наименование аэропорта РФ'] == i]['Январь - Декабрь'])
  except:
    continue

In [18]:
request

,Юрлицо,Наименование аэропорта РФ,Пассажиропоток суммарный за 2018,Грузопоток суммарный за 2018
0,ОАО «Аэропорт Архангельск»,Архангельск(Талаги),732453.0,1385.0
1,ОАО «Нарьян-Марский объединенный авиаотряд»,Нарьян-Мар,0.0,0.0
2,ОАО «2-ой Архангельский объединенный авиаотряд»,Васьково,NaN,NaN
3,ОАО «Аэросервис»,Котлас,0.0,0.0
4,ОАО «Аэропорт Лешуконское»,Лешуконское,0.0,0.0
...,...,...,...,...
277,ОАО «АС «Амур»,Ургалан,0.0,0.0
278,КП «Аэропорты Курильских островов»,Итуруп,NaN,NaN
279,ЗАО «МЕЖДУНАРОДНЫЙ АЭРОПОРТ «ДОМОДЕДОВО»,Домодедово,NaN,NaN
280,ОАО «Аэропорт Внуково»,Внуково,NaN,NaN
281,ОАО «Международный аэропорт Шереметьево»,Шереметьево,NaN,NaN

# 4. Перечислить аэропорты, где пассажиропоток больше медианы, а грузопоток меньше медианы.

In [19]:
# В new собираются ненулевые данные за 2018 год
new = request[request['Пассажиропоток суммарный за 2018'].notnull()]
new = new.loc[(new['Пассажиропоток суммарный за 2018'] != 0) & (new['Грузопоток суммарный за 2018'] != 0)]

new

,Юрлицо,Наименование аэропорта РФ,Пассажиропоток суммарный за 2018,Грузопоток суммарный за 2018
0,ОАО «Аэропорт Архангельск»,Архангельск(Талаги),732453.0,1385.0
42,ООО «Воздушные Ворота Северной Столицы»,Санкт-Петербург(Пулково),14016344.0,19637.0
46,ОАО «Аэропорт Мурманск»,Мурманск,713392.0,1287.0
50,ОАО «Комиавиатранс»,Сыктывкар,446783.0,469.0
51,ОАО «Комиавиатранс»,Воркута,17627.0,64.0
56,ОАО «Международный Аэропорт Иркутск»,Иркутск,1647187.0,6294.0
59,ОАО «АэроЧита»,Чита(Кадала),290213.0,2173.0
70,ОАО «Аэропорт Белоярский»,Белоярский,50291.0,63.0
73,ООО «Международный аэропорт Когалым»,Когалым,104388.0,177.0
76,ОАО «Надымское авиапредприятие»,Надым,138880.0,266.0
77,ОАО «Нижневартовскавиа»,Нижневартовск,495859.0,2223.0
78,ОАО «Новоуренгойский ОАО»,Новый Уренгой,702284.0,2925.0
79,ОАО «Аэропорт Сургут»,Ноябрьск,146046.0,435.0
85,ОАО «Аэропорт Сургут»,Сургут,1358938.0,2458.0
88,ОАО «Аэропорт Рощино»,Тюмень(Рощино),1527176.0,2704.0
92,ООО АП «Газпром авиа»,Ямбург,45828.0,1.0
102,"Мирнинское авиационное предприятие АК АЛРОСА"" ...",Ленск,35202.0,363.0
104,"Мирнинское авиационное предприятие АК АЛРОСА"" ...",Мирный,259115.0,5795.0
110,"Мирнинское авиационное предприятие АК АЛРОСА"" ...",Полярный,46241.0,346.0
117,Аэродром совместного базирования. в оперативно...,Тикси,13422.0,318.0
124,"ОАО Аэропорт Якутск""""",Якутск,707508.0,7055.0
130,ОАО «Международный аэропорт Курумоч»,Самара(Курумоч),2374758.0,1991.0
133,ОАО «Международный аэропорт Уфа»,Уфа,2476084.0,178.0
143,Аэропорт «Бугульма»,Бугульма,31235.0,13.0
148,ООО «Международный аэропорт Кемерово имени Ал...,Кемерово,368043.0,956.0
152,ОАО «Омский аэропорт»,Омск(Центральный),823004.0,2262.0
154,ООО «Аэропорт Стрежевой»,Стрежевой,10687.0,12.0
156,ОАО «Аэропорт Абакан»,Абакан,150533.0,638.0
165,ФКП «Аэропорт «Кызыл»,Кызыл,18963.0,10.0
173,ГП КК «КрасАвиа»,Хатанга,3931.0,331.0
193,ОАО «Белгородское авиапредприятие»,Белгород,104209.0,8.0
198,ООО «Центр Авиа»,Иваново(Южный),17287.0,147.0
210,ОАО «Аэропорт Туношна»,Ярославль(Туношна),18935.0,1933.0
215,ФКП «Аэропорты Чукотки»,Певек,17440.0,604.0
227,ПАО «Аэропорт Кольцово»,Екатеринбург(Кольцово),4598051.0,13510.0
232,ОАО «Международный аэропорт Сочи»,Сочи,5213678.0,2548.0
233,ОАО «Международный аэропорт Краснодар»,Краснодар(Пашковский),3155146.0,4836.0
237,ГУП СК «Международный аэропорт Ставрополь»,Ставрополь(Шпаковское),295659.0,541.0
239,ОАО «Аэропорт Анапа»,Анапа(Витязево),1288050.0,585.0
240,ОАО «Аэропорт Астрахань»,Астрахань(Нариманово),450159.0,576.0
243,ОАО «Международный аэропорт Волгоград»,Волгоград(Гумрак),865565.0,605.0
254,ФКП «Аэропорты Дальнего Востока»,Зея,394.0,1.0
260,КГУП «Хабаровские авиалинии»,Николаевск-на-Амуре,29694.0,29.0
263,КГУП «Хабаровские авиалинии»,Охотск,6005.0,111.0
272,ФКП «Аэропорты Дальнего Востока»,Чумикан,944.0,8.0
276,"ОАО «Аэропорт Южно-Сахалинск»,",Южно-Сахалинск(Хомутово),812971.0,7647.0

In [20]:
# Медианы пассажиропотка и грузопотока среди суммарных значений аэропортов за 2018 год
pt_median = new['Пассажиропоток суммарный за 2018'].median()
ct_median = new['Грузопоток суммарный за 2018'].median()

# Аэропорты, где пассажиропоток больше медианы, а грузопоток меньше медианы
result = new.loc[(new['Пассажиропоток суммарный за 2018'] > pt_median) & (new['Грузопоток суммарный за 2018'] < ct_median)]

print('Аэропорты, где пассажиропоток больше медианы, а грузопоток меньше медианы:\n', list(result['Наименование аэропорта РФ']))

Аэропорты, где пассажиропоток больше медианы, а грузопоток меньше медианы:
 ['Сыктывкар', 'Уфа', 'Ставрополь(Шпаковское)', 'Астрахань(Нариманово)']

# 5. Перечислить авиакомпании у которых нет типов воздушных судов зарегистрированных не в России

In [21]:
airlines = airlines[airlines['Самолеты'].notna()]
airlines

,Индекс,Название,Юридическое Название,Самолеты
551,Абакан Эир,Общество с ограниченной ответственностью «АБАК...,Абакан,"Ил-76 (7), Ми-26 (3), Ми-8 (3), Ми-8МТВ (5)"
481,Авиа Менеджмент Груп,Акционерное общество «Авиа Менеджмент Груп»,Иваново (Южный),Pilatus PC-12 (10)
554,Авиакомпания «Лайт Эйр»,Закрытое акционерное общество Авиакомпания «Ла...,Уфа,"BK-117 (1), Robinson R-44 (17), Ан-2 (7), R..."
284,Авиакомпания СОКОЛ,Закрытое акционерное общество Авиакомпания «С...,Новотитаровская-Азимут,"Ми-2 (1), Ми-8 (1)"
442,Авиакон Цитотранс,Открытое акционерное общество Авиакомпания «А...,Екатеринбург(Кольцово),Ил-76 (5)
...,...,...,...,...
526,Ямал АК ООО,Общество с ограниченной ответственностью «Авиа...,Салехард Тазовский Тарко-Сале,"AS-350 (2), Ми-8 (41), Ми-8МТВ (3)"
142,Ямал АТК ОАО,Открытое акционерное общество «Авиационная тра...,Москва (Домодедово) Салехард Тюмень(Рощино),"A-320 (7), A-321 (2), B-737 (4), CL-600-2B1..."
463,"2-й Архангельский ОАО, ОАО",Открытое акционерное общество «2-ой Архангельс...,Архангельск (Васьково),"L-410 (4), Ан-2 (6), Ми-26 (2), Ми-8 (9), ..."
239,223-й ЛО ФГКУ,федеральное государственное казенное учреждени...,Чкаловский,"Ил-62 (4), Ил-76 (5), Ту-154 (4)"
529,224-й ЛО ОАО,Открытое акционерное общество «Государственная...,Тверь(Мигалово),"Ан-124 (8), Ил-76 (17)"

In [23]:
# Список уникальных типов самолетов зарегистрированных в России
print(unique_rus_aircrafts)

['Птенец-2', 'С-2 Елочка', 'Небесный', 'Светлый', 'Сура', 'EUROSTAR', 'Pioneer 330', 'СП-30З О', 'Саргон', 'Аэропракт-20', 'Ястреб', 'Рейнджер МПВ', 'Икарус С42В', 'С22В Икарус', 'Авиатика-890СХ', 'С-2УТ Синтал', 'Х-32-912УТ Гор', 'Peregrrine SL', 'EuroStar SL', 'EuroStar SLW', 'СП-34М', 'Саванна', 'FK-9 Mark-3', 'Z-602', 'А-27МС', 'Дельфин-10', 'АС-5М Альбатрос', 'Вимана', 'Аэропракт-22L2', 'Авиатика-МАИ-890СХ', 'Жучок', 'СП-30 Эльф', 'А-27М', 'СП-30', 'Спорткруизер', 'СН-701', 'СП-30Амур1', 'NG-46', 'ЭКЛИПС', 'Alpha Trainer', 'Амик-10', 'Sky Ranger', 'Х320', 'Аэропракт-22Л2', 'ТОПОЛЬ', 'МК 192', 'СП-01(КП)', 'Р-20 "Птенец-2"', 'СТ-18', 'СКИФ', 'САПСАН', 'WT9 DS', 'Петр Первый', 'Авиатика-МАИ-890У', 'ОБ-31', 'Ан-2', 'Ан-2Т', 'СП-30 Ермак', 'Викинг', 'X-32 B-1 "Бекас"', 'Z-43', 'А-27М2', 'СК-12т3 "Орион"', 'KP-2U SOVA', 'ФОТОН', 'Касатик М-12К', 'Savannah', 'Корвет-26', 'Дельфин_', 'По-2', 'Таурус М', 'СТ-2000', 'Sky Ranger G', 'СП-30НГ', 'Ан-2ТП', 'СП-30К', 'Корвет-Л', 'СП-30Z', 'ТВС-2АМ-1', 'БЕРКУТ-1', 'NG-5BRM', 'ТВС-2МС', 'BLACKSHAPE CF300 "PRIME"', 'П2002 Сиерра', 'С-2СХ"Синтал"', 'PC-12/47', 'PC-12/47E', 'PC-12/45', 'Авиатика 890-582', 'Pilatus PC-12/45', 'PC-6/B2-H4', 'Pilatus PC-12/47E', 'Аист-410М', 'P.180', 'Piaggio FW P 149D', 'П92 Эхо Супер', 'СП-30бви', 'Х-32 Бекас', 'TL-232 CONDOR', 'ПТЕНЕЦ-2УЛ', 'Светлячок', 'ПТЕНЕЦ АВК', 'СП-30ИК "ЧИЖИК"', 'А-27М1', 'А-29', 'X-32 B-2', 'Pioneer 230 № 243', 'Pionerr 230 № 224', 'А-20 Аэропракт', 'DA 42', 'DA 42 M', 'DA 42 NG', 'Аэропракт-22L2 "ADVENTURE"', 'DA 40 NG', 'АЛГА', 'Элитар-Сигма "Сигма S.LAIM\'', 'Аэропракт-22L2 БАЛУ', 'Вирус', 'Л-13ВВМ', 'Кинетик', 'Л-13ВМ', 'Extra 300/L', 'SR22', 'P2006T', 'P2002 JF', 'EUROSTAR SLW', 'Фермер-1', 'P2002-JF', 'Фермер-2', 'Aero Commander 520', 'MU-2B-26A', 'Beech 23', 'Model 390 Premier I A', 'Арго-02', 'Фермер-3', 'PC-46-500TP', 'EA 300/SC', 'PA-32-260', 'АИ-10 РОМАШКА', 'X-32', 'С-2 Синтал', 'Элитар-Сигма', 'Бе-103', 'Элитар-202', 'Проспорт-Каб', 'B19', '750XL', 'PA-46-350P', 'TL 2000 Sting S4', 'К-10 Свифт', 'TWINSTAR MARK-3 Classic', 'Че-259', 'СП-30АС', 'Че-257', 'ALBATROS-SX', 'Джет Фокс-97', 'СП-30 Ирбис', 'DV 20 KATANA', 'Корвет-2', 'Як-54', 'Як-52', 'L-200D', 'РА-28-180', 'Скиф 1', 'РА-46-500ТР', 'PA-32R-301', "PZL-104 'Wilga-35A'", 'АЭРОПРАКТ-22Л2', 'Х-32 "Колибри"', 'CТРИЖ', 'Х-34', 'Х-32 "Бекас-В"', 'Х-32 "Бекас-Г"', 'EV-97 EuroStar SL', 'Х-32 "Бекас-Д1"', 'Х-32 "Бекас-Е1"', 'С-182TD', 'PA-46', 'SportCruiser', 'А-10', 'С-182S', 'МЦС-130 "Беркут"', 'СП-30П', 'СП-55М', 'ОВП-100', 'РУСЬ', 'ВИТЯЗЬ', 'Аэропракт-22L2-1', 'СК-12т4 Орион"', 'СП-30 Сокол', 'Аэропракт-22Л', 'АС-11', 'ОСА', 'СП-38 УТ', 'СП-30В', 'Че-22 "EAGLE"', 'СТ 2000 С', 'СП-38', 'Синтал C-2', 'ЧИЖИК', 'Пеликан-4А', 'МАИ-890УМ', 'Б-2', 'СП-32УТ', 'Пеликан-2Б', 'АНТ', 'SKY RANGER-Северок', 'Аэропракт-27МБ', 'Че-22', 'Skhrab', 'Ш-2А "Шмель"', 'СП-37УТА', 'ВИРАЖ В-1', 'АС-2 Сигма', 'Скай Рейнджер', 'Skyranger M-1', 'CH-701 "STOL"', 'СТ-19', 'СТ-20', 'И-3', 'ПС-2Б Акробастер', 'АРГ-101 "Кармастер"', 'СТ-2', 'SKY RANGER', 'СТ-23', 'МАИ-890 ЧАЙКА', 'СТ24', 'Х-32 КРЕЧЕТ', 'СТ-22', 'Х-32 БЕРКУТ', 'СТ-17', 'HS-125-700B', 'BAe 125-800A', 'HS-125-700A', 'EMB-135BJ', 'HONEY BEE H2', 'СП-22', 'Model 390 (Premier I)', 'EMB-550', 'Super Petrel LS', 'И-15БИС', 'B300', 'HS125', 'ДИТ', 'KitFox II КРл-19', 'В-35.2004', 'Ан-2П', 'БЕКАС 103', 'EMB-120ER', 'БЕКАС 102', 'БЕКАС 101', 'EV-97 EuroStar SL+', 'VIPER SD-4', 'SPORTSMAN', 'X-32-912 Бекас', 'ПЕРЕПЕЛ', 'Sport Star Plus', 'Птенец 2 РТ 912', 'FROGGY', 'СП-30Амур2', 'Д-360', 'Д-358', 'Д-140', 'КОЛИБРИ.', 'Фаэта', 'СК-01', 'ВАЛДАЙ', 'АЭРОПРАКТ А22-912', 'МАП-32-912сх', 'ViAL', 'F-02', 'Рейнджер ДК', 'А-22СВ', 'РейнджерВВ', 'СП-30 РЫСЬ', 'СП-30М-1', 'ГУСЬ-1', 'СП-2008', 'J 450', 'ЕХ-350', 'WT-9 DYNAMIC', 'ММ-330', 'А-22 Аэропракт', 'СП-33', 'Х-32 "СТРИЖ"', 'Кронавиа-8', 'РАДИАН', 'Кронавиа-7', 'Л-42', 'Че-27М2 СА-002', 'АИ-9', 'Питер ВМЦ-100', 'ZODIAK 601 UL', 'Скайренжер', 'SKYRANGER', 'Х-32 "АИСТ"', 'Ежик', 'LA-8C-RS', 'СП-30 МРИЯ', 'STOLL-701S', 'НС-3', 'НС-2', 'Р-20 "Птенец-2П"', 'Спектр-30', '"АВИА"-АЗЦ-14', 'СтэП', 'А-20', 'СА-8', 'Иволга', 'СП-34 "СТРИЖ"', 'НС-1', 'С-402B', 'СОКОЛ 80-84', 'Х-32 B-3 "Бекас"', 'ХАИ-48', 'АЭРОПРАКТ-22', 'А-22КМ', 'X-32Д "Бекас"', 'Х-32-912', 'А-890', 'Warrior', 'Динамик', 'С-182 ТАВ', 'А-890УТ Авиатика', 'А-52', 'МАКС-32-912', 'Х-32 "Бекас-Соло"', 'PA-28-140', 'МИР-32-912', 'Pioneer 230, №227', 'Як-18А', 'Х-32 "Выша"', 'Х-32 "Орьев"', 'А-22Л', 'СК-12 Орион', 'Х-32 АРЦЕУЛОВ К.К', 'SAMBA XXL', 'Х-32 Славянка', 'Беркут', 'Корвет-К', 'СТ-25', 'СТ-31', 'SkyMax', 'СТ-32', 'СП-30 СХ-Т', 'STOL CH 701', 'СП-24', 'Piper Cub', 'Cessna-172N', 'Sunny', 'X-32 B-4 "Бекас"', 'Чирок', 'ШАРК', 'Стрекоза', 'СР-30', 'Пеликан-2', 'SHARK', 'С-150 Жорик', 'Бланик Л-13М', 'ФаворитF-1', 'СИГМА-Л', 'KITFOX 2015', 'INSIGNIA', 'Cetus-1000', 'Long-EZ', 'Sky Wolf', 'SCHEIBE SF25A', 'Кронавиа-9', 'Cetus A700', 'АЛЛЕГРО', 'ФВС', 'Бриз', 'Х-32 ЛАСТОЧКА', 'СР-29', 'Х-32 Бекас-К', 'BORA', 'X-32 "Бекас-Х"', 'А-27-М-4', 'ЛУНЬ', 'Х-32 "Бекас-ПВЕ"', 'JF 91D', 'LAMBADA', 'Странник', 'Леон', 'СуперКэт', 'NG TPAIL 001', 'АЭРОПРАКТ-22L2M', 'ДРАКОН', 'СК-12 "Орион"', 'Ф-32 "Агро"', 'Ф-32У "Агро"', 'Як-12М', 'Сигма-4 СМ', 'Икар', 'ГЕНЕЗИС', 'Корвет-К3', 'Х-32 Снегирь', 'МиГ-15', 'АИ-10', 'Птенец-2 АС', 'СМ-2000П', 'А-41', '"ZODIAK" CH-701 STOL', 'ТЕРМИК', 'RANS S-10 SAKOTA', 'Л-13М', 'SportStar Plus', 'Cessna-FR-172E', 'ФХ-32 "АГРО"', 'ПАЙПЕР КЭБ', 'Х-32 Бекас-АC', 'МУХА', 'СП-30А', 'Х-32 Бекас "Призрак"', 'ЛУНЬ-Б', 'Авиатика С-5', 'Одиссей', 'Синтал С-2 01', 'КМН-172', 'РАДУГА', 'Д-3', 'СП-45', 'СП-46', 'АМК-5', 'DRAGONFLY', 'СП 30ZZM', 'СП-30ZM', 'Дельфин-3', 'ТУКАНО', 'С-2', 'СН-650320', 'Ил-14', 'Синтал Ю-2', 'СП-44', 'СП-30 МАРС', 'СП-52', 'СП-30ВТ', 'F-11 ODISSEY', 'СКАЙ-РЕЙНДЖЕР', 'С-18Т1', 'Шершень', 'МАП-32-912', 'ТУРУХТАН II', 'ТУРУХТАН III', 'СП-37П', 'Т-10 КАЙРА', 'Джабиру-450', 'АП-22', 'СЛ-39ВМ1', 'TL-2000 STING carbon RG', 'Харченко', 'Сигма-4', 'СП-34В', 'Ю-87 Б-2 Штука', 'БЕКАС', 'А-27М4', 'СП-30Б', 'РА-23-250', 'SA-26AT', 'RV-8', 'PA-28R-201', 'PA-23-250', 'Gardan GY80-160', 'Mitsubishi MU-2B-35', 'Stinson 108-2', 'PA-46-500TP', 'В200', 'LAKE 250', 'L-13 SE Vivat', 'PA-28-181', 'DC3C-S4C4G', 'FORECASTER', 'Piper PA-28R-200', 'Zlin Z 37 T', '58Р', 'ДРАГОНФЛАЙ', 'Акбар', 'Х-32 B-5 "Бекас"', 'SOFIA-601XL', 'Сигма-6', 'СП-36К "Гренадёр"', 'Х32 ВОРОН', 'СП-42', 'Ан-3Т', 'IKARUS C-42B', 'СР-СПАРТАК', 'MAEFIN TOPFUN', 'СП-34НГ', 'А-22МК', 'Х-32 БАКЛАН', 'СП-31', 'СКС-1-02', 'SKY', 'СКС-1-01', 'Бюкер-131С', 'FLY SYNTHESIS STORCH 582', 'Питтс-12', 'СНЕГИРЬ', 'СОЛОВЕЙ', 'Х-32 Альбатрос', 'Скайрейнджер', 'ЧЕ-22-КД', 'Дим-Джет-195', 'ОВП', 'FR-172K', 'СП30В', 'Аэропракт-22LS (A-22LS)', 'PJ-2', 'Р-20 "Птенец-2М"', 'Стерх', 'Чибис', 'СП-38АК', 'L-250', 'J-3', 'Авиатика 890У', 'СП-30 "Стрелец"', 'СП-34', 'ZODIAC 650 RE', 'СП-34К', 'Х-32 Авангард', 'Старлинг', 'Онежец', 'Х-32 "МИКС-3"', 'Птенец-2УБ', 'Skyboy', 'Чиж', 'Арго-02цм', 'C-172 Stranger', 'Питенпол', 'C-172 Tiger', 'Бекас-1', 'Бекас-2', 'Як-52 ПМ2', 'Грач', 'Аэропракт-22L', 'К58', 'УТ-18', 'СА-91', 'С-15', 'С-172 "SIMBA"', 'В-2', 'Dynamic-WT-9HK', 'А-4', 'РЕМЕЗ-1', 'СА-1', 'Альфа тренер', 'Свифт К-10', 'CH 701 STOL', 'Че-25К', 'PIONEER 330 №020', 'СИРИУС', 'Л-200А Морава', 'АИ-10 Икар', 'Корвет-J', 'СП-90', 'Рейнджер М', 'Sportcruiser 01-AP', 'СМ-94-И', 'КВС-52', 'Сейбр С-60', 'Х-01 Беркут', 'Стриж_', 'СП-52Л', 'Commuter-151', 'СМ-92', 'СМ-94-1', 'СП-35', 'Финист-004', 'С-172', '777 AVIA', 'ИМ-180', 'WarriorII', 'Су-31', 'Агро-1', 'Агро-2', 'СМ-92Т', 'Че-22Р', 'Т-52', 'СП-32П', 'Ла-8', 'ER 300/L', 'А-33', 'СП-2007', 'СП-250', 'СТ-27', 'ПС-52', 'Л-200А', 'АП-21 Зенит', 'ТВС-2МС-12', 'По-2ВС', 'Су-31К', 'Т-18', 'ARROW', 'С-172К', 'СП-27', 'Тренер-Т2', 'Л-29 Viper', 'СР-31', 'Стерх-С1', 'Орион', 'Авиатика-МАИ-890', 'Генерал', 'К-18', 'Яша', 'Еким', 'А-33-011', 'Тайгер-Мот', 'П-96 Гольф-100', '18Т', 'В-35.2006', 'Синица-7', 'МВЕН-2 Фермер', 'СП-25', 'СП-26', 'Вильга-35А', 'Сигма-4 Дуэт', 'С-182ТД', 'АДС-100 Пегас', 'СП-129', 'Як-30', 'СМ-18Т', 'Че-25', 'Аист-2', 'Корвет-64', 'Z-326', 'Л-39', 'С-18Т.2', 'С-18Т.3', 'LARK', 'Скай Мастер', 'ЯК18ТГО', 'ЯК18ТГС', 'СП-36У', 'Че-22 Корвет', 'С-421', 'PA-31T', 'Дрозд', 'С-182', 'Ан-24РВ', 'PA-23 Aztec', 'СТ-26', 'Р-25', 'СР-32', 'С42В', 'Стриж-1', "С-172 'Скайхок'", 'КОАЛА', 'FALCON-900B', 'FALCON 900EX EASy', 'FALCON-7X', 'ТЛ-2000', 'ML-29', 'Yak-18T', 'Sky Arrow 450T', 'СТВ-35А', 'С-150М', 'Авиатика 890 Брянск', 'Феликс', 'Б-32 Ирина', 'Л-200Д', 'Х-32 Бекас-3', 'F-172', 'Х-32 B-6 Бекас', 'СП-55Д', 'РОМАНОВ', 'СП-52М', 'СП-52МВС', 'Р-20', 'SPORTSTAR', 'Ацтек', 'Falcon 900LX', 'Торга-1', 'СП-32', 'Литл-Джет-185', 'Литл-Джет-186', 'Катран', 'Sportcruiser 02-RS', 'Сиерра 200', 'СП-36УТ', 'АВИАТИКА-МАИ-910', 'СВ-3000', 'Триумф', 'Z-142', 'Skylane', 'Commander', 'ЛС-1 Ворон', 'DA20/100 Katana', 'А-32 Сканер', 'СП-14М', 'Cessna 172S', 'VARI EZE', 'Л-6СВ', 'Л-6М', 'УТ-18М', 'SP-55M', 'Че-27', 'СП-38у', 'СП-30у', 'Х-32 Бекас-КМ', 'Меркурий VI-У', 'Корвет-Б3', 'Gulfstream IV-SP', 'Gulfstream V-SP', 'Gulfstream GV-SP (G550)', 'Gulfstream GVI (G650)', 'РВ-9А', 'Skywagon', 'Мермейд', 'Cetus-700', 'Питенполь', 'C-172ПР', 'СП-55', 'Скайренджер', 'Аэропракт-22ЛС', 'Аэропракт-22ЛМ', 'АЛЕКС-1', 'АЛЕКС-2', 'Грифон-100М', 'Эдельвейс', 'C-172I', 'C-172N', 'С-176 Фламинго', 'СП-24М', 'ТЛ-2000Ш', 'К-10', 'SABRINA', 'Л-4', 'Л-29Д01', 'Ц-172У', 'Ц-172М', 'И-103', 'Птенец-2мт', 'NG-4 НИОЛ-2', 'NG-4 НИОЛ-1', 'IKARUS C42B-2', 'IKARUS C42B-3', 'TAILWIND', 'Dynamic WT9', 'Ан-12БП', 'Чероки-28', 'EVROSTAR SL', 'Cessna-150M', 'Т-18М', 'А-1 Авангард', 'Ан-12Б', 'Аэропракт-22017', 'Флайт Дизайн СТЛС', 'РА36-300', 'С-188В', 'Ш-2', 'Пыжик', 'ZK-F', 'P 96 GOLF', 'Ан-12', 'Авиатика А 890', 'Сапсан Ми-001', 'Мотопланер Бланик М', 'Зодиак-601', 'NG-4 UL', 'Cetus A702', 'Л-13 Бланик.', 'VILGA 35', 'Июль-2', 'А-33М', 'ЭОЛ', 'ГОГА-МЫШКА', 'PA-18 Super Cub', 'Cherokee-28', 'РА-38', 'Зодиак 601 УМЛ', 'Б-52', 'С-150С', 'СВ-32', 'Л-29 Дельфин', 'Ан-12ТБ', 'Сигма-Классик', 'C-182RG', 'Х-32 Виват', 'Ш-1А "ШМЕЛЬ"', 'Skyhawk-172', 'Че-22 Корвет-К', 'Р 92 В "Эхо Супер"', 'Р 2002 П "Сиерра"', 'Р 2002 "Сиерра"', 'Рейнджер-Сокол', 'МП-1', 'Р 2002 ШВ Сиерра', 'Рейнджер-Т', 'СП-38К', 'А-27МК', 'СП-38 Аспект', 'СП-30 Сапсан', 'Ан-12БК', 'Чайка.', 'СП "Леон"', 'Фандор', 'Гвардия 54', 'СП-30ТЦ', 'СМ-92Т-001', 'А-22ЮС', 'МАИ 223', 'Ф-5М', 'Циклон Ц-188А', 'БП-1 Турухтан', 'С-1', 'Сокол', 'X-32 Flight', 'СМ-01 Чайка', 'NG-4', 'Тулпар-182Т', 'Red Liner', 'СВП-207Т', 'Дельфин-29', 'СП-38 Айшатик', 'Л-200АМ', 'СП-52В', 'Август', 'ГЗ-1 "Эдельвейс"', 'СП-38УТА', 'СП-39УТА', 'С-172М', 'С-52В', 'EV-97R EuroStar', 'P2002 Sierra RG de Luxe', 'P2002 Sierra RG', 'ДВ-18Т', 'Птенец-2А', 'MAULE', 'НС-4', 'STOL TROPHY 2000TT', 'Т-2', 'P92 Echo Super', 'Ан-26', 'ШХ-2', 'A-20SCSE', 'Вайпер-29', 'Скай', 'Шмелк', 'Сигма-Классик А', 'СП-52У', 'MUSKETEER', 'Шмель', 'Л-29М1', 'СП-48', 'Л-29 Центурион', 'Cetus M7', 'TL-2000 Стринг', 'МАЙКЛ-1', 'Х-32/89сх "Корвет"', 'С-210РН', 'HARTOR', 'Аэропракт А-37', 'Piper Sport', 'СК-12т5 Орион', 'C-164', 'СП-38АМ', 'Х-32-912УТ "Бекас"', 'Х-32Т Бекас', 'А-22', 'P2002 Sierra Deluxe', 'РЫЖИК', 'P2002 Sierra', 'P2008', 'СП-30УТ "Вилорик"', 'Zodiac 601XL', 'Корвет', 'ТЛ-3000 СИРИУС', 'СП-30 Семерочка', 'М-12 Касатик-Д', 'Сокол 777', 'GN-155.02', 'Корвет-ЛУ', 'СП-30М', 'Бриз М', 'С-182К', 'Авангард-2', 'Авангард-3', 'РТ-38', 'Skycruiser', 'C150H', 'ЭКОСПАС', 'СП-37М', 'Пайпер-спорт', 'Cetus-702', 'Ил-103с', 'ХАРАДА-1', 'ХАРАДА-2', 'Maule M-7-235C', 'МХ7', 'Cetus 710', 'Буревестник 22', 'Чайка 35', 'Синий ястреб-172', 'Красный Кардинал-177', 'C-152KN', 'Чиж "Цессна-172 М"', 'Чероки РА-28', '150Л Цессна', 'C-172V', 'C-400 Corvalis', 'Yak-52', 'БелкАН-01', 'М-101Т "Гжель"', 'Миротворец', 'Унжа', 'P2002 RG', 'Любава', 'С-185 "Медведь"', 'Extra 330/LC', 'СП-43', 'Беркут СМ-451', 'Сигма-5', 'ТЛ-2000 "Стинг"', 'КС-201м', 'СП-30 Дрозд', 'МС-893', 'C-150KN', 'С-182С', 'STB-20', 'М-7', 'Мушкетер', 'Лебедь', 'Афалина', 'А-2 Авангард', 'Софинад', 'И-16', 'И-153 "Чайка"', 'МиГ-3', 'Cessna-172D', 'BL-330LC', 'NG 4 HD', 'БВА', 'Sport Cruizer SA', '001 Лена', 'JT-18 джокер', 'Дельфин-2', 'Зодиак', 'Альбаз', 'ШАГ-150 "Белый Ветер"', 'ПЗЛ-104 И-35 Иволга-35М', 'СН-650', 'Л-42М', 'В-18Т', 'Спорт', 'Як-12А', 'RV-7A', 'А-890У', 'СХ-55', 'DA-40F', 'Рейджер АВ', 'Зодиак СН-601ТМ', 'СН-701ТМ', 'СП-36У Air Ranger', 'СП-77', 'YR-1', 'YR-2', 'Ромашка', 'Cessna 172RG', 'М-12 Касатик-ШУМЕР', 'Як-52 "Прототип"', 'Пилигрим-06', 'Аэропракт-22LS', 'Самара', 'СН-701Т', 'Цикада М3', 'L200D Феникс', 'C-172P', 'Сталкер', 'C-172Z', 'Л-29 JET', 'Cetus-1002', 'С-15 А', 'Sky Arrow 450TS', 'Аэропракт A-22LS', 'С-150 Акробат', 'C-172M', 'A-22LS', 'A22LS-90TM', 'СК Круизер', 'NG 5 LSA', 'РА-46', 'GM-17 Viper', 'С182Р', 'TL-2000 Стинг', 'Arrow-IV', 'FK9 ELA', 'ПИПИСТРЕЛ ТАУРУС Т503', 'C-172L', 'IAR-823', 'R-G', 'Maule M-7-235B', 'Сириус РА-28', 'Як-18ТК', 'СП-30 Десяточка', 'S10-VT', 'СП-38ТМ', 'СП-38УМ', 'А-22ДД', 'Юнона', 'Piper L-4', 'С-150 Тайфун', 'Sierra C24R', 'С172С', 'Вильга 35А14', 'Christen Eagle-2', 'Вильга 35М14', 'ЯК-18ТСС', 'Л-42М Синяя птица', 'CN-150L/T', 'Goos', 'С-152', 'СП-581', 'F15-F Сапсан', 'Ск-12т6 Орион', 'Dag-555', 'AT01 Aquila A-210', 'C-172U', 'Cetus Evolution', 'С-172ХР', 'C-182Q', 'М-18Т', 'СП-40', 'СП-41', 'EA 300/LC', 'ZLIN-42M', 'РВ-52', 'КВ-52', 'Икарус С42Е', 'ZODIAC CH801 XL', 'СокоЛ-29', 'А-201Д', 'Аэростар-52', 'F-52', 'Cetus-1777', 'Цикада', 'Иволга-35', 'Т-18МН', 'Centurion PA-28', 'Centurion C-172', 'Моль', 'Че-29А1', 'CH 260 Flight', 'Цессна-150М', 'Элитар-Сигма Кизляр', 'МХ-7', 'Piper Sport-V2', 'Сокол-2М', 'РС-РА-28', 'Злин-42М', 'Z-142M', 'А-33Х', 'Морава-200А', 'NP-18-2P', 'Белый лебедь', 'Л-42М СТЕРХ', 'MTR-1', 'CESSNA-182', 'Cessna-152', 'С-150 АУРА', 'HARMONY LSA', 'Ц-182П', 'Як-52 SPORT', 'Аэропрактика-222', 'ДВ-150', 'Цикада-М', 'Cessna 172E', 'Як-18Т-Мыслитель', 'Maule M-7-235', 'STINSON 108-1', 'STINSON 108-3', 'Piper PA-28-140', 'C-172 IR', 'G-202', 'Цикада-СБ', 'A-22 LS', 'Cetus A900', 'RV-9A', 'NG-4 НИОЛ-3', 'SP-91', 'C-150', 'А-27М5', 'Remos GX', 'Чайка-U206', 'А-1С 200', 'Як-52С', 'Як-18С', 'У-2', 'TUNDRA', 'Фермер-4', 'Фермер-4П', 'РА-23', 'Аэропракт-22-1', 'Сибиряк', 'GL-III', 'С-150 Ларк', 'SA-226T', 'V-39 Сокол', 'БИМБОС', 'C-150L', 'С-18Т', 'PSJ-01', 'Корвет-J2', 'А-22 Сокол', 'Cessna C-172G', 'C-172G', 'L-39D', 'АН-2Б', 'Cessna 172 BSV', 'МЦ-172 TRAINER', 'Sport Cab PA-18', 'КОНДОР-212', 'Л-44 Танаис', 'ВАД-52', 'C-172 C', 'Х-32-914 "Бекас"', 'По-2П', 'СУ-26М2', 'KITFOX 5 OUTBACK', 'А-22лс БИП', 'М-12', 'Сокол-М', 'ЛВМ-60', 'PA-28-161 (Warrior II)', 'Арчер', 'EX-360', 'Л-42М СТЕРХ-1', 'СК-12т7ш "Орион"', 'Коммандер', 'Элитар-Сигма С4Е-006', 'NG-45', 'NG-48', 'C172 R-02', 'C172 R-01', 'MZ-22LS', 'С-150КР', 'М-142', 'СЗК-4', 'ТЛМ-2000', '"Форсаж"', 'Cetus 200', 'Cetus 900', 'Cherokee-180', 'Н800', 'Че-29А2', 'Super Maule 720', 'Cetus 703', 'УТС-42 01', 'STOL CH 750', 'Virus SW', 'Авиатика-МАИ-890-СХУ', 'NG 5 BRM', 'Кардинал', 'Lake LA4-200', 'ZLIN 142', 'ТУНДРА', 'C-52', 'Бичкрафт Бонанза', 'Л-31', 'Аэропракт А-22', 'Cessna 150 LNS', 'Хохорей-180', 'Фарман-4', 'W-35A', 'С-172N', 'EA300/LP', 'C-337', 'C-377G', 'Cessna C-150L', 'Cetus A703', 'Пайпер РА-19', 'LA-4200', 'Экстрим 1', 'Aerobatic', 'SportAero 2', 'SportAero 1', 'СТРИЖ С182', 'Цессна 182А', 'Z-37A-1', 'FA-20', 'DC-3', 'Harmony', 'МАИ-223М', 'Л-29_', 'CN-150M', 'C-T206F', 'HUSKY', 'Лиман-ГЛ', 'Норд-Винд 1', 'Норд-Винд 2', 'DA20-A1', 'Шершень -1м', 'MS-885', 'C-182W', 'Yak-52B', 'С-172Р', 'Як-52Н', 'A-22LSB"Аэропракт"', 'RV-7', 'РВ-53', 'УТС-МС893А', 'АА 5', 'Ascent', 'ТВС-2МС-2', 'Pitts', 'РА-28', 'P2002-JF CS/VLA', 'Zlin-42MF', 'B-58 Baron', 'Л-42М "Игл"', 'КР-11', 'ZODIAC CH-601 XL', 'Альбатрос-01', 'E 330 LXI', 'Злинн-42М', 'Cessna-182P', 'Я52', 'Lightning', 'Л-42 Лебедянка', 'C-182S', 'ПАЙПЕР РА-18', 'MAULE MX-7-160', 'Корвет-АТ', 'EA-300', 'VP-Cherry', 'С-012 Ястреб', 'УТС-28 01', 'ТБ-10', 'AC-680V', 'Cessna C-172D', 'Cessna-172 Centurion', 'Як-40', 'Як-40К', 'Epic LT', 'DREAMER', 'REMOS-GX', 'И-7', 'РА-161', 'SKYLEADER 500', 'Альбатрос-02', 'Че-24А1', 'ARROW III', 'Hormony LSA', 'SM-337', 'CR-182', 'Exstra 300/SCE', 'C-172R-03', 'C182R-01', 'Элитар-Сигма С4Е-007', 'C-337F', 'C-185F', 'СН.801', 'C-182 L', 'NORDCES-172', 'Sky Arrow 650 TNS', 'УТС-Z142', 'Сигма-4 Баваль', 'F-150M', 'ПАЙПЕР РА-20', 'SU-29', 'SU-31', 'Гаврон', 'М7-235', 'R-GX', 'ЗОДИАК 601 XL', 'Моран MS893AA', 'C-A185F', 'ВМБ 59 Арктур', 'Cetus 1003', 'СТРЕЛА', 'Л-42М-Адмирал', 'Л-42М-Альбатрос', 'СуперКаб-36', 'КОРСАР', 'Cetus 704', 'Sky View', 'СН801', 'Лайка', 'Fokker DR.1', 'North Americfn SNJ-4', 'НАВАХО', 'C172R-04', 'NG 5 Demo', 'Sopwith Camel', 'AVRO 504K', 'По-2А', 'С-44Ф', 'Чайка-35В', 'Fokker D VII', 'КАРДИНАЛ-27', 'Л-42МШ', 'Eagle-2', 'EXTRA 300/SCE', 'C-T310R', 'М5-235С', 'RV-10', 'NG 5 Bristell', 'А-33МА', 'М-12 Касатик', 'SportStar MAX', 'Турист', 'Мастер-52', 'FY-101', 'LS-5', 'CESSNA-150F', 'C-172CT', 'SM-1019', 'F-30', 'E 330 LXK', 'Cessna 172M', 'УТСЛ-29', 'В-35С', 'МАЛ-35', 'MAULE M-6-235', 'C-182N', 'Ф-007', 'С-182М', 'Cessna 182P', 'HARMONY LS', 'С182', 'C-172H', 'Cessna 172N', 'А-12', 'Zlin Z-42M', 'Morane MS-893', 'AG-55', 'LAKE 200', 'АТ-52', 'F-37 Шмель', 'Че-29Б1', 'В-95', 'Як-52СС', 'Як-52СМВ', 'Як-12СЕ', 'CE-172', 'Zet-42', 'Стриж-5', 'CT Supralight', 'PA-34-220T', 'СА-07', 'PZL Koliber', 'А-150', 'МАРАБУ', 'С 172', 'Cueppa P2002', 'Фенёк', 'Су-29ПФ', 'Филин', 'Twin Bee', 'В-95А', 'А-33 МИКС', 'Lake Buccaneer', 'МВ-500', 'RemosGX-912', 'A-33-1', 'Commander 114', 'Cruiser', 'ZODIAC CH 650', 'Зодиак 650 ВК', 'С-172МЕ', 'Цесна 175К', 'А-44', 'Cessna-150JKS', 'Тукан', 'А-45', 'PZL-104 Вильга-35А', 'PAK-172D', 'Коммодор', 'C177/68', 'HELIO H-295', 'СП-92', 'Ермак', 'Cessna 182RG', 'C-172-MX', 'Д-36 Беркут', 'C-226T', 'Wilga 2000-1', 'Цессна172р', 'Циррус СР-22', 'LAKE BUCANEER 546', 'Цикада 22', 'Витязь-18Т', 'Z-142Б', 'Sierra P2002A', 'ПЗЛ-101А', 'Феникc', 'Пинелопа', 'Мираж-18Т', 'Lake Salmon', 'Jonathan', 'Дельфин-5', 'C-501SP', 'Aero Commander 681', 'М-12КА', 'Bonanza F33A', 'МС-890', 'Чекан 22', 'ЦСН-150', 'C172R-06', 'C172R-07', 'П-01 ВАЙПЕР', 'CESSNA 182M SKYLANE', 'СохАч-12', 'C172R-05', 'C172R-08', 'Акробат-М', 'Сокол-55М', 'PZL-101 GAWRON', 'Zlatik-150M', 'PV-10', 'С172-0381', 'ПАЙПЕР28-266-99', 'Грэй', 'Л-42МТ', 'Cessna 150L', 'Бирхок Патруль', 'C-182LY', 'Х-34 Бекас', 'Ветерок', 'Siena', 'B-33-D', 'В-35 Кузнечик', 'Ласточка.', 'BBP-45', 'C-172R ОМЕГА', 'АЭРОМАКС', 'GROSS', 'Ирис-206', 'A-22RT', 'СП-152', 'Pioneer 400, № 400', 'Jerry', 'Cessna P210N', 'F-172L', 'Феникс Ф-12М', 'C-182 Fortuna', 'Су-31МХ', 'Л-44м', 'М-6-235', 'NG-5 Bristell', 'Zenair CH-801 HD EWAG', 'КВ-12М', 'Альбатрос-1', 'АС680', 'CH-601HDS ЯстребоК', 'Socata Trinidad TB-20', 'RV-10 Анатолий', 'Ч-29К', 'B-23-S', 'ВЕ 60', 'СВС-16', 'Л-42м Мечта', 'Beech 200', 'Елена', 'ZL-142', 'CF-150K', 'Cessna T210K', 'Цессна-182Е', 'C-210F', 'П28А', 'ТВС-2ДТ', 'М5-235', 'STOL 801', 'PA-28R-180', 'MAULE MXT-7-180', 'STOL CH-801-M', 'Prolog 2002', 'VALENTIN TAIFUN 17E', 'Excelsior', 'C18052665', 'Rк-12а "Александр Невский"', 'Вальдо', 'Ла-4', 'C172H0582', 'CSS-150', 'Robin DR-360', 'Стинсон-108-1', 'Як-12м "Лель"', 'Z-142AP', 'GT-2 Aerostar', 'Reims F-172E', 'Викинг-150', 'EA 300/SCE', 'Z-142VV', 'Z-42AV', 'П-2С Акробатмастер', 'SM 1019', 'СП-91 05-01 (И-3)', 'C172RG', 'Ил-103А', 'СП-52АМ', 'STB-10', 'SpSt', 'NG 5 DELTA', 'А-48', 'А-47', 'Aeroprakt-22L2', 'РА28140-28-25583', 'Z-142SJ', 'PG-150', 'CESSNA-172G', 'VS-1', 'C-170A', 'Cessna T182T', 'Z-142A', 'В-23 Мушкетер', 'Nimbus-2000', 'A36TC "Bonanza"', 'Альбатрос-2', 'Skymaster NEO', 'Skymaster A-337', 'STOL 701CH', 'PZL-101AV', 'В-35', 'Cessna-172E', 'ГАРТ', 'Cessna 182P/Skylane', 'PA2814028-7325205', 'Ан-26Б-100', 'Rally Minerva', 'Ан-26Б', 'GuRu', 'Ан-26-100', 'ЧЕ-23м', 'Pioneer 300, № 328', 'Соката MS-893', 'Лисёнок', 'С150-М1', 'Ан-26БРЛ', 'SeaRey', 'С-72', 'Л-42м-2', 'СОКАТА-ТВ10-287', 'C-172K-1723121', 'L-13SE Vivat', 'Ан-24Б', 'СМ-26', 'Че-25С', 'Scheibe Falke SF25C', 'МУШКЕТЕР-23', 'Тэш

In [24]:
airl = []

for index, row in airlines.iterrows():
  answer = True # True - все самолеты текущей авиакомпании зарегистрированы в России, иначе False
  planes = row['Самолеты'].split(',')
  
  for i in planes:
    # Убираем из названий самолетов лишнее
    i = i.lstrip()
    ind = i.index(' ')
    i = i[:ind]
    # Если текущего самолета нет в списке уникальных самолетов, зарегистрированных в России, то answer становится False
    answer = answer and (i in unique_rus_aircrafts)
  
  # Сохраняем авиакомпанию, если все ее самолеты зарегистрированы в России
  if answer:
    airl.append(airlines.loc[index]['Индекс'])

print('Авиакомпании у которых нет типов воздушных судов зарегистрированных не в России:\n', airl)

Авиакомпании у которых нет типов воздушных судов зарегистрированных не в России:
 ['Авиакон Цитотранс', 'Авиастар-ТУ', 'Амур', 'Аэросервис (Даг.)', 'ВОЛГА-ДНЕПР', 'Грозный Авиа ОАО', 'Ижавиа ОАО', 'ИрАэро АК ЗАО', 'Летные  проверки и системы', 'Псковавиа', 'СИБИА', 'СиЛА', 'ШАР инк Лтд.', '224-й ЛО ОАО']

# 6. Выведите список: Месяц, суммарный пассажиропоток за данный месяц, аэропорт, в котором пассажиропоток в данном месяце минимальный

In [25]:
# В min_pt собираются ненулевые данные за 2007 год, т.к. по этому году наиболее полная информация
min_pt = passenger_transportation.loc[(passenger_transportation['Год периода данных'] == 2007) & (passenger_transportation['Январь - Декабрь'] != 0)]
# Список месяцев
months.pop(-1)

'Январь - Декабрь'

In [26]:
# Для каждого месяца определяется минимальный пассажиропоток и аэропорт с этим минимальным пассажиропотоком
for i in months:
  mini = min_pt[i].min()
  x = list(min_pt.loc[min_pt[i] == mini]['Наименование аэропорта РФ'])[0]
  print(f'Месяц: {i} \nСуммарный пассажиропоток за данный месяц: {round(min_pt[i].sum(), 2)} \nАэропорт с минимальным пассажиропотоком: {x} (пассажиропоток: {mini})\n')

Месяц: Январь
Суммарный пассажиропоток за данный месяц: 4290267.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 22.0)

Месяц: Февраль
Суммарный пассажиропоток за данный месяц: 3897237.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Март
Суммарный пассажиропоток за данный месяц: 4631915.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Апрель
Суммарный пассажиропоток за данный месяц: 5152085.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Май
Суммарный пассажиропоток за данный месяц: 5767910.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 30.0)

Месяц: Июнь
Суммарный пассажиропоток за данный месяц: 7367346.0
Аэропорт с минимальным пассажиропотоком: Комсомольск-на-Амуре (пассажиропоток: 0.0)

Месяц: Июль
Суммарный пассажиропоток за данный месяц: 8630900.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Август
Суммарный пассажиропоток за данный месяц: 9149516.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Сентябрь
Суммарный пассажиропоток за данный месяц: 7892758.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Октябрь
Суммарный пассажиропоток за данный месяц: 6381720.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Ноябрь
Суммарный пассажиропоток за данный месяц: 5549886.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

Месяц: Декабрь
Суммарный пассажиропоток за данный месяц: 5575594.0
Аэропорт с минимальным пассажиропотоком: Майкоп (пассажиропоток: 0.0)

# 7. Вывести список: тип аэропорта, средний грузопоток в месяц в аэропортах данного типа

In [27]:
request['Тип'] = airports['Тип'].apply(lambda x: str(x).replace('  ', ' ').rstrip().lstrip())
request = request[request['Грузопоток суммарный за 2018'].notna()]

request

,Юрлицо,Наименование аэропорта РФ,Пассажиропоток суммарный за 2018,Грузопоток суммарный за 2018,Тип
0,ОАО «Аэропорт Архангельск»,Архангельск(Талаги),732453.0,1385.0,В
1,ОАО «Нарьян-Марский объединенный авиаотряд»,Нарьян-Мар,0.0,0.0,В
3,ОАО «Аэросервис»,Котлас,0.0,0.0,Г
4,ОАО «Аэропорт Лешуконское»,Лешуконское,0.0,0.0,Г
5,ФКП «Аэропорт Амдерма»,Амдерма,0.0,0.0,В
...,...,...,...,...,...
272,ФКП «Аэропорты Дальнего Востока»,Чумикан,944.0,8.0,Е
274,ФКП «Аэропорты Дальнего Востока»,Экимчан,93.0,0.0,Д
275,КП «Аэропорты Курильских островов»,Южно-Курильск(Менделеево),0.0,0.0,Г (горный)
276,"ОАО «Аэропорт Южно-Сахалинск»,",Южно-Сахалинск(Хомутово),812971.0,7647.0,А
277,ОАО «АС «Амур»,Ургалан,0.0,0.0,Г

In [28]:
# Группировка по типу и вычисление среднего внутри групп
averages = request.groupby('Тип')['Грузопоток суммарный за 2018'].mean()/12
print(averages)

Тип
B              45.083333
А             378.944444
А-1             0.000000
А-2            14.833333
Б             193.805556
Б (горный)    106.166667
Б-1           165.916667
В              37.714539
Г               1.122312
Г (горный)      0.000000
Д               0.000000
Е               0.023810
Name: Грузопоток суммарный за 2018, dtype: float64